version: "3.8"

services:
  app:
    container_name: frontend-famfund-admin
    image: mjkundta/frontend-famfund-admin:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
